resolver: lts-19.19

packages:
- '.'

flags:
  cryptonite:
    use_target_attributes: false
  matrix-sized:
    parallel: false

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  7dbe3dfdcdfc0a5f28bfe3c6162cf9f9a56bda91

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  453223010d0f3b94d43fecc65e1e105fbb7e6354

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  ffea141128e7b63a21162c76358194ad433a19a9

#- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
#  commit:  a567e632e1167d7105974e1acf87be9f356fc494
- '../Taiji-RNA-seq'

#- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
#  commit:  0362dc0fc0024ff474f4d582d048852444eac5b9
- '../Taiji-scRNA-seq'

#- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
#  commit:  eed40db1d944330724664278834162f4ea352bee
- '../Taiji-scATAC-seq'

- git:     https://github.com/Taiji-pipeline/Taiji-fusion.git
  commit:  a2ef0b3c162028ba1bd89c7f151b3e703f4cde8d

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  a2fcc435fc752152f06f14e0cfa56153fa0b7d02

- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  2c26f974936b20bdae3e17c92d8ff43c83587348

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  de809a8ff9486c8bdce9a620ca7357a61bc64abb

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  b8949495069a61e56ae125ee5e4f87b9a423868f
  subdirs:
      - bioinformatics-toolkit

- git:     https://github.com/Taiji-pipeline/ftp-client.git
  commit:  9c4c577ea39c85e5da28b7fd76c54b31743fc9df
  subdirs:
      - ftp-client-conduit

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.17.1

- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  8de080874b7671186af8dc04deb471e909b10719
- distributed-process-monad-control-0.5.1.3
- network-transport-tcp-0.8.0
- distributed-static-0.3.9

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  6c617a15a99596c9fb50ef1034e9da33c1111f7e
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
